runtime: nodejs18

instance_class: F1

service: default

default_expiration: '12h'

automatic_scaling:
  max_instances: 1
  min_instances: 1
  max_idle_instances: 1
  min_idle_instances: 0

handlers:
  - url: /_next/static
    static_files: .next/static
    upload: public
  - url: /.*
    secure: always
    script: auto