POST http://localhost:8081/posts
Content-Type: application/json

{
  "title": "二番目の投稿",
  "contents": "Clean Architecture 少しわかってきた"
}

###
PUT http://localhost:8081/posts/4
Content-Type: application/json

{
  "id": 4,
  "title": "ブログを開設しました！やったぜ！",
  "contents": "これからよろしくお願いします！"
}

###
DELETE http://localhost:8081/posts/2
Content-Type: application/json

{}
